language: bash
sudo: true
dist: trusty

env:
  - EOS_BRANCH=v1.4.1 PYTHON_VERSION=3.5.6

script:
  - docker build -t e2e --build-arg eos_branch=${EOS_BRANCH} --build-arg eosfactory_branch=${TRAVIS_PULL_REQUEST_BRANCH} --build-arg python_version=${PYTHON_VERSION} --build-arg test_pypi_password=${TEST_PYPI_PASSWORD} ./tests/integration/
  - docker run -ti e2e "python /opt/eosfactory/tests/01_hello_world.py"
  - docker run -ti e2e "python /opt/eosfactory/tests/02_eosio_token.py"
  - docker run -ti e2e "python /opt/eosfactory/tests/03_tic_tac_toe.py"
